---
site:
    blog_title: mtc
    author: Michael Crilly
    tld: mcrilly.me
    contact:
       email: michael@mcrilly.me
       twitter: "@mrmcrilly"
       irc: movedx/Freenode/##security

template:
    localPath: templates
    name: development

index:
    publishPath: website

articles:
    localPath: articles
    publishPath: website

pages:
    localPath: pages
    publishPath: website