---
site:
    blog_title: mtc
    author: Michael Crilly
    tld: http://mcrilly.me
    contact:
       email: michael@mcrilly.me
       twitter: "@mrmcrilly"
       irc: movedx/Freenode/#puppet

template:
    localPath: "../data/templates"
    name: development

index:
    publishPath: "../data/website"

articles:
    localPath: "../data/articles"
    publishPath: "../data/website"
    template: article.html

pages:
    localPath: "../data/pages"
    publishPath: "../data/website"
    template: page.html