---
site:
    blog_title: mtc
    author: Michael Crilly
    tld: mcrilly.me
    contact:
       email: michael@mcrilly.me
       twitter: "@nonexistent"
       irc: movedx/Freenode/##security

template:
    localPath: templates
    name: development

articles:
    localPath: articles
    publishPath: website
    indexPath: website