---
core:
  templates:
    foundin: /home/mcrilly/.rita/templates/
    use: development
  content:
    foundin: /home/mcrilly/.rita/content/

site:
  blog_title: mtc
  author: Michael Crilly
  tld: http://mcrilly.me
  contact:
    email: michael@mcrilly.me
    twitter: "@mrmcrilly"
    irc: movedx/Freenode/##security

